name=RS_JSON
version=0.9
author=Vladimir Mladenov <v_mladenov@mail.bg>
maintainer=Vladimir Mladenov <v_mladenov@mail.bg>
sentence=Master-Slave JSON serial transfer library
paragraph=Master-Slave JSON serial transfer library
category=Communication
url=https://github.com/vlmm/rs_json
architectures=avr,stm32,esp8266
